CREATE TABLE public.REST_DB_TASKS(TASK_ID integer,WRPK_ID integer,  TASK_NAME VARCHAR (500));

CREATE TABLE public.REST_DB_TOOLS(TOOL_ID integer, TASK_ID integer,TOOL_NAME VARCHAR (500));

CREATE TABLE public.REST_DB_WORKPACKAGES(WRPK_ID integer, WRPK_BARCODE VARCHAR(50), WRPK_NAME VARCHAR (500));

CREATE TABLE public.LP_AIRCRAFT(LPAC_AC_REG_CD VARCHAR(10), LPAC_ASSMBL_CD VARCHAR(80), LPAC_AUTHORITY_CD VARCHAR (8));

