CREATE TABLE public.REST_DB_TOOLS(TOOL_ID integer, TASK_ID integer,TOOL_NAME VARCHAR (500));

CREATE TABLE public.LP_WORK_PACKAGE(LPWP_BARCODE VARCHAR(80),LPWP_NAME VARCHAR(500),LPWP_STATUS VARCHAR(12),LPWP_LOCATION VARCHAR(2000),LPWP_DATE_TIME_START DATE,LPWP_DATE_TIME_END DATE);

CREATE TABLE public.LP_AIRCRAFT(LPAC_AC_REG_CD VARCHAR(10), LPAC_ASSMBL_CD VARCHAR(80), LPAC_AUTHORITY_CD VARCHAR (8));

CREATE TABLE public.LP_TASK(LPTK_CODE integer,LPTK_BARCODE VARCHAR(80),LPTK_CODE_MXI DECIMAL(10),LPAC_AC_REG_CD VARCHAR(10),LPWP_BARCODE VARCHAR(80),LPTK_NAME VARCHAR(500),LPTK_STATUS VARCHAR(12),LPTK_TASK_TYPE VARCHAR(16),LPTK_DUE_DATE DATE,LPTK_DUE_DATE_EXT DATE,LPTK_DUE_DATE_FNL DATE,LPTK_YIELD FLOAT(53),LPTK_DURATION FLOAT(53),LPTK_BARCODE_DVR VARCHAR(80),LPTK_DUE_DATE_DVR DATE,LPTK_PRIORITY DECIMAL(2),LPTK_SCHED_STATUS VARCHAR(30));