INSERT INTO public.REST_DB_TASKS(TASK_ID,WRPK_ID, TASK_NAME) VALUES (1,1,'TASK1');
INSERT INTO public.REST_DB_TASKS(TASK_ID,WRPK_ID, TASK_NAME) VALUES (2,2,'TASK2');
INSERT INTO public.REST_DB_TASKS(TASK_ID,WRPK_ID, TASK_NAME) VALUES (3,2,'TASK3');
INSERT INTO public.REST_DB_TASKS(TASK_ID,WRPK_ID, TASK_NAME) VALUES (4,3,'TASK4');

